export enum SERVICE_TRANSACTION_TYPES {
  BONUS = 'BONUS',
  RACE_PRIZE = 'RACE_PRIZE',
  CASHBACK = 'CASHBACK',
  LOYALTY_REWARD = 'LOYALTY_REWARD',
  REFERRAL_REWARD = 'REFERRAL_REWARD',
  VIP_WELCOME_BONUS = 'VIP_WELCOME_BONUS',
  WAGER_RACE_PRIZE = 'WAGER_RACE_PRIZE',
  FREE_SPINS = 'FREE_SPINS',
}

export enum SERVICE_TRANSACTION_STATUS {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum CASHBACKCLAIMTYPES {
  INSTANT = 'instant',
  DAILY = 'daily',
  WEEKLY = 'weekly',
  MONTHLY = 'monthly',
}

export enum CASHBACKTYPES {
  DEFAULT = 0,
  TIME_BOOST = 1,
  GAME_BOOST = 2,
}
