export enum UTMSource {
  GOOGLE = 'google',
  FACEBOOK = 'facebook',
  SMS = 'sms',
  EMAIL = 'email',
  WHATSAPP = 'whatsapp',
  TELEGRAM = 'telegram',
  INSTAGRAM = 'instagram',
  YOUTUBE = 'youtube',
  TIKTOK = 'tiktok',
  TWITTER = 'twitter',
  LINKEDIN = 'linkedin',
  PINTEREST = 'pinterest',
  REDDIT = 'reddit',
  BLOG = 'blog',
  SNAPCHAT = 'snapchat',
  DISCORD = 'discord',
  X = 'x',
}
